apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one-deployment
  namespace: ingress-basic
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
        tier: backend
    spec:
      containers:
      - name: app-one
        image: app-one
        args:
        - "-text=apple"
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "60"]
        ports:
        - containerPort: 5678
      terminationGracePeriodSeconds: 70
