apiVersion: v1
kind: Service
metadata:
  name: app-one
  namespace: ingress-basic
  # annotations:
  #   alb.ingress.kubernetes.io/healthcheck-path: /health-check.html
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 5678
    protocol: TCP
  selector:
    app: app-one
