apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: esc-server
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/june2/k8s.git
    targetRevision: HEAD
    path: argocd/charts/esc-server

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-basic

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
    - CreateNamespace=true

